// import localFont from "next/font/local";
import Navbar from "@/components/Home/Navbar/Navbar";
import "./globals.css";
import Footer from "@/components/Home/Footer/Footer";

// const geistSans = localFont({
//   src: "./public/fonts/GeistVF.woff", // Use the absolute path from the public folder
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./public/fonts/GeistMonoVF.woff", // Use the absolute path from the public folder
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar /> */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
